pipeline {
    agent any

    environment {
        SQL_SA_PASSWORD = credentials('sql-sa-password')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install prerequisites') {
            steps {
                powershell '''
                    ./scripts/01-install-prereqs.ps1
                '''
            }
        }

        stage('Configure SQL') {
            steps {
                powershell """
                    ./scripts/02-configure-sql.ps1 -SqlPassword '${SQL_SA_PASSWORD}'
                """
            }
        }

        stage('Run Aras Installer') {
            steps {
                powershell '''
                    ./scripts/03-install-aras.ps1
                '''
            }
        }

        stage('Run ArasUpdate') {
            steps {
                powershell '''
                    ./scripts/04-run-arasupdate.ps1
                '''
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
    }
}
